version: '3'

services:
  api:
    command: ''

  terraform:
    image: hashicorp/terraform:light
    working_dir: /home/terraform
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./terraform:/home/terraform:delegated

  kubectl:
    build:
      context: .
      dockerfile: Dockerfile.kubectl
    environment:
      KUBECONFIG: /home/.kube/config
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    entrypoint: kubectl
    volumes:
      - ./terraform/kube:/home/.kube:delegated

  aws:
    image: mesosphere/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: eu-west-1

