version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - ./:/app:delegated
      - api_node_modules:/app/node_modules
    command: /bin/sh -c 'yarn && yarn dev'
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'

volumes:
  api_node_modules:
